name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: bash scripts/install.sh
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
