name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: Lint Shell Scripts and Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './config'
        env:
          SHELLCHECK_OPTS: -e SC2016 -e SC1090

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
